// Code generated by "stringer -type=BackingCall -linecomment"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownBackingCall-0]
	_ = x[CallBTreeFIFO-1]
	_ = x[CallBTreePriority-2]
	_ = x[CallBboltFIFO-3]
	_ = x[CallBboltPriority-4]
}

const _backingCall_name = "UnknownNewBTreeFIFONewBTreePriorityNewBboltFIFONewBboltPriority"

var _backingCall_index = [...]uint8{0, 7, 19, 35, 47, 63}

func (i BackingCall) String() string {
	idx := int(i) - 0
	if idx >= len(_backingCall_index)-1 {
		return "BackingCall(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _backingCall_name[_backingCall_index[idx]:_backingCall_index[idx+1]]
}
