// Code generated by "stringer -type=OpCall -linecomment"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownOpCall-0]
	_ = x[CallPush-1]
	_ = x[CallPop-2]
	_ = x[CallPeek-3]
	_ = x[CallExists-4]
	_ = x[CallDel-5]
	_ = x[CallNotEmpty-6]
	_ = x[CallNotFull-7]
	_ = x[CallClose-8]
	_ = x[CallClear-9]
}

const _opCall_name = "UnknownPushPopPeekExistsDelNotEmptyNotFullCloseClear"

var _opCall_index = [...]uint8{0, 7, 11, 14, 18, 24, 27, 35, 42, 47, 52}

func (i OpCall) String() string {
	idx := int(i) - 0
	if idx >= len(_opCall_index)-1 {
		return "OpCall(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _opCall_name[_opCall_index[idx]:_opCall_index[idx+1]]
}
